### ISSUE TITLE
Some pod names will throw bad substituion error when running tests on GKE.

### ISSUE THREAD

**Issue by zheli** [controlplaneio/netassert#16]
Thanks for the great work! I had an issue running this tool on pod name that doesn't contain a hypen sign ("-"). Here is my test yaml file:

```bash
k8s:
  deployment:
    zhe:abc:
      google.com: 443
```

And it throws exception like:
`environment: line 9: HOST_MAP_zhe:abc: bad substitution`

I tried to fix it but seems like other part stopped working after that. Would be great to get some pointers from you:)

**Comment by zheli** [comment]
Make a quick fix: https://github.com/controlplaneio/netassert/pull/17

Not sure if this introduces any new issues. My tests passed at least :)

**Comment by prit342** [comment]
API and test input has changed after v2.0.0 release
